server:
  port: 8083

spring:
  application:
    name: hub-service
profiles:
  active: local
  config:
    import: optional:file:./.env
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/