spring:
  config:
    import:
      - optional:file:.env[.properties]
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:mem:item_db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
#data:
#  redis:
#    # Redis 서버가 실행되는 호스트 (일반적으로 로컬)
#    host: localhost
#    # Redis 서버 포트 번호 (기본값)
#    port: 6379
#    # database: 0 # 기본 DB 인덱스 (필요 시 주석 해제)
#
## 6. Redisson 클라이언트 설정 (분산 락/캐싱 사용 시)
#redisson:
#  singleServer:
#    address: redis://localhost:6379
